<?php
/**
 * CabalEngine CMS
 * 
 * @version 1.2.0
 * @Mod author Rooan Oliveira / Original author Lautaro Angelico <http://lautaroangelico.com/>
 * @copyright (c) 2013-2019 Lautaro Angelico, All Rights Reserved
 * 
 * Licensed under the MIT license
 * http://opensource.org/licenses/MIT
 */

// CabalEngine CMS Tables Prefix
define('WE_PREFIX', '');

// CabalEngine CMS Tables
define('CABALENGINE_BANS', WE_PREFIX.'CABALENGINE_BANS');
define('CABALENGINE_BAN_LOG', WE_PREFIX.'CABALENGINE_BAN_LOG');
define('CABALENGINE_BLOCKED_IP', WE_PREFIX.'CABALENGINE_BLOCKED_IP');
define('CABALENGINE_CREDITS_CONFIG', WE_PREFIX.'CABALENGINE_CREDITS_CONFIG');
define('CABALENGINE_CREDITS_LOGS', WE_PREFIX.'CABALENGINE_CREDITS_LOGS');
define('CABALENGINE_CRON', WE_PREFIX.'CABALENGINE_CRON');
define('CABALENGINE_DOWNLOADS', WE_PREFIX.'CABALENGINE_DOWNLOADS');
define('CABALENGINE_FLA', WE_PREFIX.'CABALENGINE_FLA');
define('CABALENGINE_NEWS', WE_PREFIX.'CABALENGINE_NEWS');
define('CABALENGINE_PASSCHANGE_REQUEST', WE_PREFIX.'CABALENGINE_PASSCHANGE_REQUEST');
define('CABALENGINE_PAYPAL_TRANSACTIONS', WE_PREFIX.'CABALENGINE_PAYPAL_TRANSACTIONS');
define('CABALENGINE_PLUGINS', WE_PREFIX.'CABALENGINE_PLUGINS');
define('CABALENGINE_REGISTER_ACCOUNT', WE_PREFIX.'CABALENGINE_REGISTER_ACCOUNT');
define('CABALENGINE_VOTES', WE_PREFIX.'CABALENGINE_VOTES');
define('CABALENGINE_VOTE_LOGS', WE_PREFIX.'CABALENGINE_VOTE_LOGS');
define('CABALENGINE_VOTE_SITES', WE_PREFIX.'CABALENGINE_VOTE_SITES');
define('CABALENGINE_ACCOUNT_COUNTRY', WE_PREFIX.'CABALENGINE_ACCOUNT_COUNTRY');
define('CABALENGINE_NEWS_TRANSLATIONS', WE_PREFIX.'CABALENGINE_NEWS_TRANSLATIONS');